site_name: c-pro
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: True
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path:
      - _src/Chapter_01/
      - _src/Chapter_02/
      - _src/Chapter_03/
      - _src/Chapter_04/
      - _src/Chapter_05/
      check_paths: True

# Page tree
nav:
  - Home: index.md
  - Docs:
    - Chapter 1: 
      - Example 1: 
        - ``` --8<-- "EX1_01.c" ```
     
    - Chapter 2: 
      - Example 1: --8<-- "EX2_01.c"
    - Chapter 3: 
      - Example 1: --8<-- "EX3_01.c"
    - Chapter 4: 
      - Example 1: --8<-- "EX4_01.c"  
      
