site_name: c-pro
theme:
  name: material
repo_url: https://github.com/Karthik-d-k/c-pro
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: True
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path:
      - _src/Chapter_01/
      - _src/Chapter_02/
      - _src/Chapter_03/
      - _src/Chapter_04/
      - _src/Chapter_05/
      
      check_paths: True

# Social links
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Karthik_d_k
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/karthik-d-k-319853166/      

# Page tree
nav:
  - Home: index.md
  - Docs:
    - Chapter 1: 
      - Example 1: Chapter_01/EX1_01.md
      - Example 2: Chapter_01/EX1_02.md
      - Example 3: Chapter_01/EX1_03.md
      - Example 4: Chapter_01/EX1_04.md
      - Example 5: Chapter_01/EX1_05.md
      - Example 6: Chapter_01/EX1_06.md
      - Example 7: Chapter_01/EX1_07.md
      - Example 8: Chapter_01/EX1_08.md
      - Example 9: Chapter_01/EX1_09.md
      - Example 10: Chapter_01/EX1_10.md
      - Example 11: Chapter_01/EX1_11.md
      - Example 12: Chapter_01/EX1_12.md
      - Example 13: Chapter_01/EX1_13.md
      - Example 14: Chapter_01/EX1_14.md
      - Example 15: Chapter_01/EX1_15.md
      - Example 16: Chapter_01/EX1_16.md
    - Chapter 2: 
      - Example 1: Chapter_02/EX2_01.md
      - Example 2: Chapter_02/EX2_02.md
      - Example 3: Chapter_02/EX2_03.md
      - Example 4: Chapter_02/EX2_04.md
      - Example 5: Chapter_02/EX2_05.md
      - Example 6: Chapter_02/EX2_06.md
      - Example 7: Chapter_02/EX2_07.md
      - Example 8: Chapter_02/EX2_08.md
      - Example 9: Chapter_02/EX2_09.md
      - Example 10: Chapter_02/EX2_10.md
    - Chapter 3:      
      - Example 1: Chapter_03/EX3_01.md
      - Example 2: Chapter_03/EX3_02.md
      - Example 3: Chapter_03/EX3_03.md
      - Example 4: Chapter_03/EX3_04.md
      - Example 5: Chapter_03/EX3_05.md
      - Example 6: Chapter_03/EX3_06.md
    - Chapter 4:  
      - Example 1: Chapter_04/EX4_01.md
      - Example 2: Chapter_04/EX4_02.md
      - Example 3: Chapter_04/EX4_03.md
      - Example 4: Chapter_04/EX4_04.md
      - Example 5: Chapter_04/EX4_05.md
    - Chapter 5:
      - Example 1: Chapter_05/EX5_01.md
