site_name: My Docs
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path:
      - _src/Chapter_01/
      check_paths: True
